const express=require('express');const cors=require('cors');const app=express();
const FRONTEND_ORIGIN=process.env.FRONTEND_ORIGIN||'*';
app.use(cors({origin:FRONTEND_ORIGIN==='*'?true:[FRONTEND_ORIGIN],credentials:true})); app.use(express.json());
app.get('/',(req,res)=>res.status(200).send('OK'));
app.use('/api/auth',require('./src/routes/auth'));
const { verifySession }=require('./src/lib/jwt'); const { prisma }=require('./src/lib/db');
app.get('/api/user/me',async(req,res)=>{const cookie=req.headers.cookie||'';const sc=cookie.split(';').map(s=>s.trim()).find(s=>s.startsWith('session='));
  if(!sc) return res.status(401).json({user:null}); const token=decodeURIComponent(sc.split('=')[1]); const payload=verifySession(token); if(!payload) return res.status(401).json({user:null});
  const u=await prisma.user.findUnique({where:{id:payload.uid}}); return res.json({user:u?{vk_id:u.vk_id,firstName:u.firstName,lastName:u.lastName,balance:u.balance}:null});});
const PORT=process.env.PORT||3001; app.listen(PORT,()=>console.log('Auth server :'+PORT));